AllCops:
  TargetRubyVersion: 2.6.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'env.rb'
  SuggestExtensions: false

Metrics/BlockLength:
  Max: 40

Metrics/MethodLength:
  Enabled: false
  Max: 15

Layout/LineLength:
  Enabled: false
  Max: 100

Metrics/AbcSize:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
