# Required
micropub_token_endpoint: https://indieauth.com/token

# Global options used if not set or overwritten on a per-site basis later
# permalink_style: "/:title"        # Jekyll permalink style as per your site's _config.yml
full_image_urls: true             # Include site_url in image paths
download_photos: false            # Ensure linked images are added to repo
# image_dir: "assets/images"               # Directory in to which images will be saved. Default: images
posts_dir: "_posts"               # Directory in to which posts will be saved. Default: _posts
syndicate_to_bridgy: false        # Syndicate post using Brid.gy. Default: false
bridgy_options:
  bridgy_omit_link: false         # Disable link back to post. Opts: true|false|maybe. Default: false
  bridgy_ignore_formatting: false # Disable the plain text whitespace and formatting. Opts: true|false. Default: false

# Individual site-specific configuration
sites:
  thesite:
    github_repo: hoschi-it/hoschi-it.de                   # Required for each site
    site_url: "https://hoschi-it.de"                      # Required for each site
    permalink_style: "pretty"                             # Overrides global set above
    full_image_urls: true                                 # Overrides global set above
    image_dir: "assets/images"                            # Overrides global set above
