
name: Linters

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  rubocop:
    name: RuboCop Action
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - name: Run Rubocop
        uses: andrewmcodes/rubocop-linter-action@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
