
name: Linters

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  rubocop:
    name: RuboCop Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Rubocop
        uses: andrewmcodes/rubocop-linter-action@v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
